SilkNetwork/Silk-Core

- src/Makefile.am
Temporarily remove unit testing in make file.
> [Unit Test] disable for now

- doc/build-windows.md
- doc/release-notes/release-notes-1.0.0.0.md
> [Doc] Add Windows build document

- src/chainparams.cpp
Fixes newer boost builds with c++11
https://github.com/bitcoin/bitcoin/commit/a2b04ddfe6452e7d6274f4096bf3f2aee695a6d9
Tested on Ubuntu and OSX.
#16
> Update to base58prefixes to vectors

- src/chainparams.cpp
Correct Base58 Params
Params were not set correctly in previous commit.
Addresses now generate correctly and sending is possible.
> Correct Params

- silk-qt.pro
Rename and remove elements of the qt pro
This isnt urgent and the qt pro is only used for debugging in qtcreator
> Amend qt.pro file for debugging in QtCreator Pt1

- README.md
Updates the main readme PoS minimum maturity time to 1 hour.
> [Doc] Update main PoS min maturity time

- src/util.cpp
Adds a silk.conf file is missing in the default directory.  Fixes issue #20 
Still testing, please do not merge.
> Add silk.conf file is missing

- src/chainparams.cpp
> Add DNS Seeders

- src/qt/silkgui.cpp
Fix for Issue https://github.com/SilkNetwork/Silk-Core/issues/39
https://github.com/SilkNetwork/Silk-Core/issues/39
Tested on OS X. Built, ran wallet, opened RPC Console, shutdown wallet and observed RPC Console close before final shutdown completed.
#39 
- Does the knowledge base need an update?
No
- Does this PR add or change dependencies?
No
- Does this PR change or fork the blockchain
No
> Add RPCConsole to SilkGUI::closeEvent

- silk-qt.pro
Updates the Qt project file so we can run silk-qt with the debugger UI.
> [Debug] Update Qt project file to run with debugger UI.

- Makefile.am
Fixes issue with make clean.
Fixes issue tasks: #43
> [Make] Fix make clean issue #43

- depends/packages/qt.mk
- depends/patches/qt/configure-xcoderun.patch
To fix any compilation issues that may be persistent when compiling with XCode 8
https://github.com/bitcoin/bitcoin/pull/8990
N/A
#
- Does the knowledge base need an update? No
- Does this PR add or change dependencies? No
- Does this PR change or fork the blockchain No
> [Compiling][XCode][macOS] Fix Compiling on XCode 8

- doc/build-windows.md
To update the documentation for building Windows on WSL
https://github.com/bitcoin/bitcoin/pull/8935
N/A
#
- Does the knowledge base need an update? No
- Does this PR add or change dependencies? No
- Does this PR change or fork the blockchain No
> Documentation: Building on Windows with WSL

- src/Makefile.am
- src/crypto/aes.cpp
- src/crypto/aes.h
- src/crypto/ctaes/COPYING
- src/crypto/ctaes/README.md
- src/crypto/ctaes/bench.c
- src/crypto/ctaes/ctaes.c
- src/crypto/ctaes/ctaes.h
- src/crypto/ctaes/test.c
- src/test/crypto_tests.cpp
As mentioned in the aforementioned title
Based on https://github.com/bitcoin/bitcoin/commit/6bec172eb95e195847bb6dd6d4e62ada79c98c6d
Ubuntu 16.04 Running on VMWare Fusion running on macOS Sierra
- Does the knowledge base need an update? No
- Does this PR add or change dependencies? No
- Does this PR change or fork the blockchain? Umm.. no
> [ctAES] Add ctAES Library and Associated Crypter Implementation

- src/Makefile.am
- src/crypto/aes.cpp
- src/crypto/aes.h
- src/crypto/ctaes/COPYING
- src/crypto/ctaes/README.md
- src/crypto/ctaes/bench.c
- src/crypto/ctaes/ctaes.c
- src/crypto/ctaes/ctaes.h
- src/crypto/ctaes/test.c
- src/test/crypto_tests.cpp
**THIS PULL REQUEST IS ONLY FOR REFERENCE ONLY (AND FOR CODE INSPECTION) - NOT MEANT TO BE MERGED STANDALONE, INSTEAD LOOK AT PR #71**
As mentioned in the aforementioned title
Based on https://github.com/bitcoin/bitcoin/commit/6bec172eb95e195847bb6dd6d4e62ada79c98c6d
Ubuntu 16.04 Running on VMWare Fusion running on macOS Sierra
- Does the knowledge base need an update? No
- Does this PR add or change dependencies? No
- Does this PR change or fork the blockchain? Umm.. no
> [Ref][ctAES] Add ctAES Library and Associated Crypter Implementation

- src/torcontrol.h
Fixes shutdown issue where wallet is monitoring/listening and will not close socket.
No.
Tested locally on OSX El Capitan 10.11.6
No but this is an Issue (urgent).
> Set Tor Default Monitoring to False

- depends/packages/libevent.mk
- depends/packages/packages.mk
- depends/patches/libevent/libevent-2-fixes.patch
- depends/patches/libevent/reuseaddr.patch
- silk-qt.pro
To Update Documentation and Compilatory Files to reflect changes
Fix code from my last merged PR. 
Cross-compilation is tested on Ubuntu 16.04 (Cross-compiling for Windows)
- Does the knowledge base need an update? Yeah!
- Does this PR add or change dependencies? This fixes that automatically
- Does this PR change or fork the blockchain? How??? It literally can't
> [Compilation] Update Documentation and Compilatory Files to reflect changes

- src/qt/guiutil.cpp
- src/qt/silkgui.cpp
Update `DNS` -> `dDNS` and `name` -> `name registered on the dDNS`.
> [Qt] Update verbiage for DNS and send to name

- src/chainparams.cpp
Deploy testnet for Silk. Cloud node = 188.166.173.136.
> [TestNet] New testnet for Silk.

- src/qt/locale/silk_de.ts
- src/qt/locale/silk_es.ts
- src/qt/locale/silk_fr.ts
- src/qt/locale/silk_he.ts
- src/qt/locale/silk_it.ts
- src/qt/locale/silk_ru.ts
Add several translations for `Enter a Silk address or name registered on the dDNS.`  More translations are needed.
> [Qt] Translations for new verbiage
